generateOres = true

[ores]
generateAntimony = true
generateBauxite = false
generateCopper = false
generateLead = false
generateLigniteCoal = true
generateNickel = false
generateSalt = false
generateSilver = false
generateTin = false
